### ISSUE TITLE
One concern about your measurements of the images at each stage

### ISSUE THREAD

**Issue by hongliliu** [ALMA-IMF/notebooks#1]
Hi Adam,
     I first listed your measurements at the very end.
     From your measurements, I found the peak flux doesn't change any more from iter3 (keeping at 0.4010 Jy/beam), however, the dynamical range is still increasing with each iteration. I was wondering if the increasing dynamical range is caused by the decrease of the rms rather than improved by something to do with the selfcal?

pk/rms= 589.6, pk/mad= 870.7, pk=0.266 Jy / beam, total=176.968 Jy / beam, postotal=1310.711 Jy / beam, rms=0.00045 Jy / beam, mad=0.00031 Jy / beam, beam=0.29x0.26
pk/rms=1227.0, pk/mad=2761.8, pk=0.409 Jy / beam, total=176.580 Jy / beam, postotal=869.431 Jy / beam, rms=0.00033 Jy / beam, mad=0.00015 Jy / beam, beam=0.29x0.26
pk/rms=2297.3, pk/mad=3527.9, pk=0.410 Jy / beam, total=283.565 Jy / beam, postotal=735.067 Jy / beam, rms=0.00018 Jy / beam, mad=0.00012 Jy / beam, beam=0.29x0.26
pk/rms=3740.7, pk/mad=4218.7, pk=0.410 Jy / beam, total=398.153 Jy / beam, postotal=712.431 Jy / beam, rms=0.00011 Jy / beam, mad=0.00010 Jy / beam, beam=0.29x0.26
pk/rms=3847.3, pk/mad=4346.9, pk=0.410 Jy / beam, total=408.235 Jy / beam, postotal=713.132 Jy / beam, rms=0.00011 Jy / beam, mad=0.00009 Jy / beam, beam=0.29x0.26
pk/rms=4593.7, pk/mad=4685.6, pk=0.410 Jy / beam, total=448.358 Jy / beam, postotal=707.358 Jy / beam, rms=0.00009 Jy / beam, mad=0.00009 Jy / beam, beam=0.29x0.26
pk/rms=5397.1, pk/mad=5412.0, pk=0.409 Jy / beam, total=450.818 Jy / beam, postotal=671.579 Jy / beam, rms=0.00008 Jy / beam, mad=0.00008 Jy / beam, beam=0.29x0.26

**Comment by keflavich** [comment]
Yes, the change in peak/mad is showing changes in the mad (rms), not in the peak.  That is exactly what we want, though: that _is_ the improvement selfcal is supposed to yield.  However, in this case, it is a mix of self-calibration-based improvement and deeper cleaning; both contribute to the lower RMS.

**Comment by hongliliu** [comment]
Thanks for the explanations. What I mentioned about no change in peak flux is actually no increase in peak flux (I should have specified it). From your above explanations, could I understand that the peak flux does not necessarily increase with each iteration of selfcal but the rms is supposed to decrease if the selfcal does help in improving the final image?

**Comment by keflavich** [comment]
Broadly correct. The peak flux _may_ increase, but it's not guaranteed to.
 In this case, it looks like all changes to the peak flux happened in the
first phase self cal iteration.  That's likely to happen often since the
brightest peak can dominate the self cal solution.
